### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by jsonpreet** [singh-saheb/tgd_covid_tracker_app#1]
![Screenshot_1](https://user-images.githubusercontent.com/26606638/78919096-0b8ee100-7aaf-11ea-87de-c2dacaa7c816.png)

**Comment by singh-saheb** [comment]
@harpreet9629  please check if you have written the correct API address and also make sure you have a good internet connection. Get back to me if the problem still persists :)

**Comment by singh-saheb** [comment]
the api is updated.
