### ISSUE TITLE
Search text not visible if selected theme is dark

### ISSUE THREAD

**Issue by dpbangera95** [singh-saheb/tgd_covid_tracker_app#3]
![Simulator Screen Shot - iPhone 11 - 2020-04-21 at 14 03 19](https://user-images.githubusercontent.com/39554591/79844197-fa13d600-83d8-11ea-9b10-59211da63652.png)

**Comment by singh-saheb** [comment]
You need to explicitly override the appBartheme method in SearchDelegate 

I'll commit the changes today 😊

**Comment by singh-saheb** [comment]
The changes are now committed and error resolved 😊
