### ISSUE TITLE
Search Bar Text

### ISSUE THREAD

**Issue by imsikun** [singh-saheb/tgd_covid_tracker_app#4]
The search bar text is not visible if we turn the dark mode on and tried to search the country.
![bug](https://user-images.githubusercontent.com/34686558/86017814-2172c900-ba42-11ea-91c0-df49d189c823.png)

**Comment by singh-saheb** [comment]
You need to override the appBarTheme method in the search delegate class. I guess I have added the changes in the code as well. You can refer to thegrowingdeveloper.org and search for the blog. I have mentioned all the required steps
